In [1]:
print("Hello World")

Hello World


In [2]:
name = "Sharad"

In [3]:
print(name)

Sharad


In [4]:
import numpy as np

In [5]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [list1, list2]

a = np.array(list3)

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

# Rows x Columns -> (Rows, Columns)

(2, 3)

In [8]:
# 1D Array
array_1D = np.array([1,2,3])

# 2D Array
array_2D = np.array([[1,2], [3,4]])

# 3D Array
array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [9]:
array_1D, array_2D, array_3D

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [10]:
array_1D.shape, array_2D.shape, array_3D.shape

((3,), (2, 2), (2, 2, 2))

In [11]:
# Create the list automatically
list_auto = np.arange(10)

# Starting, Stopping, Stepping
list_auto_2 = np.arange(3, 10, 2)

In [12]:
list_auto

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
list_auto_2

array([3, 5, 7, 9])

In [14]:
list_1 = [1,2,3,4,5]
list_1_np = np.array([1,2,3,4,5])

In [15]:
print(type(list_1))
type(list_1_np)

<class 'list'>


numpy.ndarray

In [16]:
list_1_np.shape

(5,)

In [17]:
# Sorting
unsorted_array = np.array([29, 10, 5, 56, 88, 75])
unsorted_array

array([29, 10,  5, 56, 88, 75])

In [18]:
sorted_array = np.sort(unsorted_array)

In [19]:
display(sorted_array)
display(unsorted_array)

array([ 5, 10, 29, 56, 75, 88])

array([29, 10,  5, 56, 88, 75])

In [20]:
# Concatenation -> Merging of multiple items (arrays)
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9])

c = np.concatenate((a, b))

In [21]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5,6]])

c = np.concatenate((a,b), axis=0)

In [23]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
c.shape

(3, 2)

In [25]:
c.ndim

2

In [26]:
c.size

6

In [27]:
list_1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [28]:
list_1 = np.arange(1, 11)
list_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Reshape an array
list_1 = np.reshape(list_1, (5,2))

In [30]:
list_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
list_1.shape, list_1.ndim, list_1.size

((5, 2), 2, 10)

In [32]:
# Create a single dimensional array
# Concatenate the array with another one dimensional array
# Sort the array
# Reshape the array into 2 dimensions (choose size in each dimension by yourself)
# Check the properties of the new array (shape, size and ndim)
# Reshape the array back to one dimension

In [33]:
# Create an array in reverse order
list_1 = np.arange(34, -1, -1)

# Create an array in normal order
list_2 = np.arange(37, 100, 3)

In [34]:
# Concatenate two one dimensional array to single array
list_3 = np.concatenate((list_1, list_2))

In [35]:
list_3

array([34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82,
       85, 88, 91, 94, 97])

In [36]:
# Sort the one dimensional array
list_3_sorted = np.sort(list_3)
list_3_sorted

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82,
       85, 88, 91, 94, 97])

In [37]:
list_3.size

56

In [38]:
# Reshape the array
list_3_reshaped = np.reshape(list_3, (8,7))

In [39]:
list_3_reshaped

array([[34, 33, 32, 31, 30, 29, 28],
       [27, 26, 25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16, 15, 14],
       [13, 12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1,  0],
       [37, 40, 43, 46, 49, 52, 55],
       [58, 61, 64, 67, 70, 73, 76],
       [79, 82, 85, 88, 91, 94, 97]])

In [40]:
# Sort the multi dimensional array
list_3_reshaped_sorted = np.sort(list_3_reshaped)

In [41]:
list_3_reshaped_sorted

array([[28, 29, 30, 31, 32, 33, 34],
       [21, 22, 23, 24, 25, 26, 27],
       [14, 15, 16, 17, 18, 19, 20],
       [ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6],
       [37, 40, 43, 46, 49, 52, 55],
       [58, 61, 64, 67, 70, 73, 76],
       [79, 82, 85, 88, 91, 94, 97]])

In [42]:
# Converting back to single dimension
list_3_single = np.reshape(list_3_reshaped_sorted, (56,))
list_3_single

array([28, 29, 30, 31, 32, 33, 34, 21, 22, 23, 24, 25, 26, 27, 14, 15, 16,
       17, 18, 19, 20,  7,  8,  9, 10, 11, 12, 13,  0,  1,  2,  3,  4,  5,
        6, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82,
       85, 88, 91, 94, 97])

In [43]:
list_3_single.shape, list_3_single.size, list_3_single.ndim

((56,), 56, 1)

In [44]:
# how to sort array in reverse order
# how to concatenate array both horizontally and vertically
# how to create an array of random elements

In [45]:
# How to sort array in reverse order
list_1 = np.array([20, 10, 45, 32, 77, 99, 82])

list_1 = np.sort(list_1)

In [46]:
# Get the items from last and copy into a another variable
list_1 = list_1[::-1]

In [47]:
# Final Reversed List
list_1  

array([99, 82, 77, 45, 32, 20, 10])

In [48]:
# Concatenation both horizonatlly and vertically

# Define the arrays
list_1 = np.array([[1, 2], [3, 4]])
list_2 = np.array([[5, 6], [7, 8]])

In [49]:
# Vertically Concatenate
list_3 = np.concatenate((list_1, list_2), axis=0)

list_3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
# Horizontally Concatenate
list_3 = np.concatenate((list_1, list_2), axis=1)

In [51]:
list_3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
# Creating an array of random element
random_array = np.random.randint(10, 50, size=(10,5))

In [53]:
random_array

array([[16, 14, 49, 42, 30],
       [42, 14, 39, 45, 37],
       [17, 38, 11, 45, 16],
       [35, 10, 31, 48, 46],
       [10, 37, 37, 20, 38],
       [24, 40, 39, 16, 40],
       [28, 35, 29, 29, 39],
       [21, 31, 31, 20, 43],
       [20, 13, 35, 15, 10],
       [29, 40, 41, 28, 18]])

In [54]:
# Split Function
array_1 = np.arange(1, 21)

In [55]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
new_array = np.array_split(array_1, 4)

In [57]:
new_array

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [58]:
array_2 = np.arange(1, 21)
array_2 = np.reshape(array_2, (5, 4))

In [59]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [60]:
new_array = np.array_split(array_2, 5)

In [61]:
new_array

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]

In [62]:
# Array Searching
random_array = np.random.randint(10, 100, size=(80))

In [63]:
random_array

array([43, 20, 99, 36, 55, 76, 71, 19, 91, 81, 49, 25, 79, 30, 55, 49, 64,
       20, 88, 28, 60, 29, 48, 34, 77, 32, 12, 21, 40, 66, 47, 11, 72, 73,
       59, 93, 73, 15, 24, 41, 71, 55, 35, 12, 79, 39, 42, 86, 71, 99, 72,
       57, 99, 81, 83, 15, 86, 68, 46, 48, 40, 39, 17, 69, 29, 16, 52, 75,
       99, 90, 77, 96, 35, 30, 48, 83, 99, 54, 24, 97])

In [64]:
# np.where() gives the indexes of the elements which passes the given condition as output instead of value
filtered_array = np.where(random_array%5 == 0)

In [65]:
filtered_array

(array([ 1,  4, 11, 13, 14, 17, 20, 28, 37, 41, 42, 55, 60, 67, 69, 72, 73]),)

In [66]:
random_array[14]

np.int64(55)

In [67]:
# Filter but get the values instead of index
# Boolean Masking

# Array Define
array_1 = np.array([1, 2, 3, 4, 5])

# Boolean Mask Define
array_2 = [True, False, True, True, False]

# Masking the array
new_array = array_1[array_2]

In [68]:
new_array

array([1, 3, 4])

In [69]:
# Create a mask based on condition
mask = random_array >= 30
mask

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True])

In [70]:
# Apply the mask
filtered_array = random_array[mask]

# Print the filtered array
filtered_array

array([43, 99, 36, 55, 76, 71, 91, 81, 49, 79, 30, 55, 49, 64, 88, 60, 48,
       34, 77, 32, 40, 66, 47, 72, 73, 59, 93, 73, 41, 71, 55, 35, 79, 39,
       42, 86, 71, 99, 72, 57, 99, 81, 83, 86, 68, 46, 48, 40, 39, 69, 52,
       75, 99, 90, 77, 96, 35, 30, 48, 83, 99, 54, 97])

In [71]:
# Doing in single step
filtered_array = random_array[random_array >= 30]
filtered_array

array([43, 99, 36, 55, 76, 71, 91, 81, 49, 79, 30, 55, 49, 64, 88, 60, 48,
       34, 77, 32, 40, 66, 47, 72, 73, 59, 93, 73, 41, 71, 55, 35, 79, 39,
       42, 86, 71, 99, 72, 57, 99, 81, 83, 86, 68, 46, 48, 40, 39, 69, 52,
       75, 99, 90, 77, 96, 35, 30, 48, 83, 99, 54, 97])

In [73]:
# Universal Functions (ufunc)

# Normal Way without using numpy to add two different arrays
array_1 = [1, 2, 3, 4, 5]
array_2 = [10, 20, 30, 40, 50]

sum_array = []
for index, value in enumerate(array_1):
    sum_value = array_1[index] + array_2[index]
    sum_array.append(sum_value)

sum_array

[11, 22, 33, 44, 55]

In [85]:
# Add two different arrays using Numpy ufunc

array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([10, 20, 30, 40, 50])
array_3 = np.array([5, 6, 7, 8, 9])

sum_array = np.add(array_1, array_2)

# Add the third array again
sum_array = np.add(sum_array, array_3)


# Subtract two arrays
difference_array = np.subtract(array_2, array_1)

# Multiply two arrays
product_array = np.multiply(array_1, array_2)

# Divide Two arrays
division_array = np.divide(array_2, array_1)

# Remaining functions
# power, mod, remainder, divmod, absolute, 

divmod_array = np.divmod(array_1, array_3)

display(sum_array)
display(difference_array)
display(product_array)
display(division_array)
display(divmod_array)

array([16, 28, 40, 52, 64])

array([ 9, 18, 27, 36, 45])

array([ 10,  40,  90, 160, 250])

array([10., 10., 10., 10., 10.])

(array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))

In [102]:
# Rounding Decimals
array_1 = np.array([10.58781, 4.000001])

# Truncate (trunc)
truncated_array = np.trunc(array_1)

# Rounding (round)
# rounding to 0 decimals
rounded_array_0 = np.round(array_1)

# rounding to 1 decimal
rounded_array_1 = np.round(array_1, 1)

# Floor
floor_array = np.floor(array_1)

# Ceiling
ceil_array = np.ceil(array_1)

display(truncated_array)
display(rounded_array_0)
display(rounded_array_1)
display(floor_array)
display(ceil_array)

array([10.,  4.])

array([11.,  4.])

array([10.6,  4. ])

array([10.,  4.])

array([11.,  5.])

In [107]:
# LCM, GCD

number_1 = 32
number_2 = 64

lcm = np.lcm(number_1, number_2)
gcd = np.gcd(number_1, number_2)

display(lcm)
display(gcd)

np.int64(64)

np.int64(32)

In [111]:
# Reduce
array_1 = np.array([16, 20, 24, 32, 64, 88])
lcm = np.lcm.reduce(array_1)
gcd = np.gcd.reduce(array_1)
sum_elements = np.add.reduce(array_1)

display(lcm)
display(gcd)
display(sum_elements)

np.int64(10560)

np.int64(4)

np.int64(244)